[tab]
active    = { fg = "#819090", bg = "#2B2B2B" }
inactive  = { fg = "#8C8C8C", bg = "#2B2B2B" }

[status]
primary	  = { normal = "#8C8C8C", select = "#819090", unset = "#5F5F5F" }
secondary = { normal = "#819090", select = "#819090", unset = "#819090" }
tertiary  = { normal = "#657B83", select = "#657B83", unset = "#657B83" }
body      = { normal = "#2B2B2B", select = "#2B2B2B", unset = "#2B2B2B" }
emphasis  = { normal = "#819090", select = "#819090", unset = "#819090" }
info      = { normal = "#668899", select = "#668899", unset = "#668899" }
success   = { normal = "#708030", select = "#708030", unset = "#708030" }
warning   = { normal = "#997000", select = "#997000", unset = "#997000" }
danger    = { normal = "#AF5F00", select = "#AF5F00", unset = "#AF5F00" }
separator = { opening = "", closing = "" }

[progress]
gauge = { fg = "#5F5F5F", bg = "#2B2B2B" }
label = { fg = "#819090", bold = true }

[selection]
hovered = { fg = "#2B2B2B", bg = "#819090" }

[marker]
selecting = { fg = "#708030", bg = "#708030" }
selected  = { fg = "#997000", bg = "#997000" }

