# General Prompt Formatting
format = """
$hostname\
$directory\

$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$custom\

$sudo\

$fill\
$git_branch\
$git_status\
$git_commit\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = true

# Hostname
[hostname]
ssh_only = true
format = "[󰢥](fg:#aa2b3339 bg:none)[█](fg:#d3c6aa bg:#aa2b3339)[$ssh_symbol$hostname](bold bg:#d3c6aa)[󰢣](fg:#d3c6aa bg:none)"
disabled = false

# Directory
[directory]
format = "[$path]($style)[ 󰷏 ](bg:#aa2b3339 fg:#7fbbb3)"
style = "fg:#d3c6aa bg:#aa2b3339 bold"
truncation_length = 3
truncate_to_repo = false
read_only = " "

# Character (Prompt symbol)
[character]
success_symbol = "[ ](#a7c080 bold)"
error_symbol = "[ ](#e67e80 bold)"

[line_break]
disabled = false

[fill]
symbol = ' '
style = 'bold #a7c080'

[cmd_duration]
min_time = 1
format = "[$duration]($style) [󱑂 ](bg:#aa2b3339 fg:#dbbc7f)"
disabled = false
style = "fg:#d3c6aa bg:#aa2b3339 bold"

# Git Branch
[git_branch]
format = " [$branch]($style) [](bg:#aa2b3339 fg:#7fbbb3)"
style = "fg:#d3c6aa bg:#aa2b3339"

# Git Status
[git_status]
format = " [$all_status$ahead_behind]($style) [ ](bg:#aa2b3339 fg:#7fbbb3)"
style = "fg:#d3c6aa bg:#aa2b3339"
conflicted = "="
ahead = "⇡ ${count}"
behind = "⇣ ${count}"
diverged = "⇕⇡ ${ahead_count}⇣${behind_count}"
up_to_date = "󰄸 "
untracked = "? ${count}"
stashed = "󰲻 "
modified = "! ${count}"
staged = "+ ${count}"
renamed = "» ${count}"
deleted = "󱟃 ${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "fg:#83c092"

# Symbols for other services
[aws]
symbol = "  "

[python]
format = "via [ Python $version](bold #a7c080)"
style = "bold #a7c080"
disabled = true

[nodejs]
format = "via [ Node.js $version](bold #a7c080)"
style = "bold #a7c080"
disabled = true

[docker_context]
symbol = " "
format = "via [$symbol$context]($style)"
style = "bold #83c092"
only_with_files = true
disabled = false
