add_newline = false
format = """
[█ ]\
(bold bg:black fg:blue)\
[󰊠 󱙝 󰊠 󱙝 ]\
(bold bg:black fg:white)\
[█]\
(bold bg:bright-blue fg:black)\
[\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
]\
(bold bg:none fg:black)\
[]\
(bold bg:none fg:black) \
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$fill\
[]\
(bold bg:none fg:white)\
[󱑍 ]\
(bold bg:white fg:black)\
[ $time ]\
(bold bg:white fg:black)\
[█](bold bg:none fg:yellow)
[󰮯 ](bold bg:none fg:white)\
$singularity\
$kubernetes\
$directory\
$status\
$character
"""

[fill]
symbol = " "

[username]
show_always = true
style_user = "bold bg:black fg:white"
style_root = "bold bg:black fg:white"
format = "[$user]($style)"

[git_branch]
symbol = " "
format = " on [$symbol$branch]($style) "
style = "bold bg:blue fg:black"

[git_commit]
style = "bold bg:blue fg:black"

[git_state]
style = "bold bg:blue fg:black"

[git_status]
style = "bold bg:blue fg:black"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[time]
disabled = false
format = "[$time]($style)"
style = "bg:white fg:black"

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "./"
style = "bold bg:none fg:yellow"

[status]
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[󱁂 ](bold white)"
error_symbol = "[󱁂 ](bold red)"
vicmd_symbol = "[󱁂 ](bold yellow)"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[lua]
symbol = " "
