format = """
[█](fg:#002B36)\
$directory\
[ ](fg:#002B36 bg:#01AF87)\
$git_branch\
$git_status\
[ ](fg:#01AF87 bg:#01AFAF)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[ ](fg:#01AFAF bg:#01AFD7)\
$docker_context\
[ ](fg:#01AFD7 bg:#01AFFF)\
$time\
[ ](fg:#01AFFF)\
"""
 
# Disable the blank line at the start of the prompt
# add_newline = false
 
 
[directory]
style = "bg:#002B36 fg:#86AEFE"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"
 
# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "📄 "
"Downloads" = "📥 "
"Music" = "🎵 "
"Pictures" = "📷 "
 
[c]
symbol = "© "
style = "bg:#6295CB fg:#23303A"
format = '[$symbol ($version) ($style)'
 
[docker_context]
symbol = "🐳 "
style = "bg:#099CEC"
format = '[$symbol $context ]($style) $path'
 
[elixir]
symbol = "💧 "
style = "bg:#4B295D"
format = '[$symbol ($version)]($style)'
 
[elm]
symbol = "🌳 "
style = "bg:#55D6A7 fg:#23303A"
format = '[ $symbol ($version) ]($style)'
 
[git_branch]
symbol = ""
style = "bg:#55D6A7 fg:#23303A"
format = '[$symbol $branch ]($style)'
 
[git_status]
style = "bg:#55D6A7 fg:#23303A"
format = '[($all_status$ahead_behind )]($style)'
 
[golang]
symbol = "🐹 "
style = "bg:#67CFDC fg:#23303A"
format = '[$symbol ($version) ]($style)'
 
[haskell]
symbol = "λ "
style = "bg:#55D6A7 fg:#23303A"
format = '[$symbol ($version) ]($style)'
 
[java]
symbol = "☕ "
style = "bg:#55D6A7 fg:#23303A"
format = '[$symbol ($version)]($style)'
 
[julia]
symbol = "ஃ "
style = "bg:#55D6A7 fg:#23303A"
format = '[$symbol ($version)]($style)'
 
[nodejs]
symbol = ""
style = "bg:#87C149 fg:#23303A"
format = '[$symbol ($version)]($style)'
 
[nim]
symbol = "👑 "
style = "bg:#EBCD00 fg:#23303A"
format = '[$symbol ($version)($style)'
 
[rust]
symbol = "🦀"
style = "bg:#FF5F00 fg:#23303A"
format = '[$symbol ($version)($style)'
 
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#01AFFF fg:#23303A"
format = '[$time]($style)'


