add_newline = false
format = """
[╭─](bold #EBDBB2)\
$username\
$hostname\
$directory\
[\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
]\
(bold bg:none fg:white)\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$fill\
(fg: black)
[│](bold #EBDBB2)
[╰─](bold #EBDBB2)\
$singularity\
$kubernetes\
$character\
$status
"""

[fill]
symbol = " "

[username]
style_user = "bold #D28D93"
style_root = "bold #EBCB8B"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
style = "bold #D28D93"
format = "[@](bold #D28D93)[$hostname]($style) [in](#EBDBB2) "
disabled = false

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold bg:none fg:green"

[git_commit]
style = "bold bg:none fg:blue"

[git_state]
style = "bold bg:none fg:cyan"

[git_status]
style = "bold bg:none fg:blue"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[time]
disabled = false
format = "$time"

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "./"

[status]
disabled = false

[line_break]
disabled = true

[character]
success_symbol = "[](bold #EBDBB2)"
error_symbol = "[](bold fg:red)"

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[lua]
symbol = " "
