[colors.primary]
background = '#0A2A2A'
foreground = '#81B5AC'

[colors.normal]
black   = '#0A2A2A'
red     = '#FF4433'
green   = '#1CA595'
yellow  = '#C4A000'
blue    = '#2AA1AE'
magenta = '#E92C85'
cyan    = '#32A198'
white   = '#81B5AC'

[colors.bright]
black   = '#4E7171'
red     = '#FF5733'
green   = '#26D9A3'
yellow  = '#FFD700'
blue    = '#33C3C1'
magenta = '#FF77A8'
cyan    = '#56D9C7'
white   = '#D3E0E0'
