[colors.primary]
background = '#343F44'
foreground = '#D8CAAC'

[colors.normal]
black   = '#374247'
red     = '#E67E80'
green   = '#A7C080'
yellow  = '#DBBC7F'
blue    = '#7FBBB3'
magenta = '#D699B6'
cyan    = '#83C092'
white   = '#D8CAAC'

[colors.bright]
black   = '#374247'
red     = '#E67E80'
green   = '#A7C080'
yellow  = '#DBBC7F'
blue    = '#7FBBB3'
magenta = '#D699B6'
cyan    = '#83C092'
white   = '#D8CAAC'
