[font]
size = 12

builtin_box_drawing = true

normal = { family = "Iosevka IBM", style = "Regular" }
bold = { family = "Iosevka IBM ", style = "Bold" }
italic = { family = "Iosevka IBM ", style = "Italic" }
bold_italic = { family = "Iosevka IBM ", style = "Bold Italic" }

offset = { x = 0, y = 1 }
glyph_offset = { x= 0, y= 1 }

